### ISSUE TITLE
Native linker errors preventing compiling for iOS Device

### ISSUE THREAD

**Issue by yozzozo** [Microsoft/mobile-center-sdk-xamarin#118]
Hi,

When I add the Microsoft.Azure.Mobile, Microsoft.Azure.Mobile.Analytics, and Microsoft.Azure.Mobile.Crashes packages to my iOS project, switch the Xamarin Studio active configuration to Debug / Device, and hit build all, I get this:

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSAnalytics. The symbol '_OBJC_CLASS_$_MSAnalytics' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSCrashes. The symbol '_OBJC_CLASS_$_MSCrashes' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSDevice. The symbol '_OBJC_CLASS_$_MSDevice' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSErrorAttachment. The symbol '_OBJC_CLASS_$_MSErrorAttachment' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSErrorBinaryAttachment. The symbol '_OBJC_CLASS_$_MSErrorBinaryAttachment' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSErrorReport. The symbol '_OBJC_CLASS_$_MSErrorReport' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSException. The symbol '_OBJC_CLASS_$_MSException' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSLogger. The symbol '_OBJC_CLASS_$_MSLogger' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSMobileCenter. The symbol '_OBJC_CLASS_$_MSMobileCenter' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSServiceAbstract. The symbol '_OBJC_CLASS_$_MSServiceAbstract' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSStackFrame. The symbol '_OBJC_CLASS_$_MSStackFrame' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSWrapperExceptionManager. The symbol '_OBJC_CLASS_$_MSWrapperExceptionManager' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSWrapperLogger. The symbol '_OBJC_CLASS_$_MSWrapperLogger' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5211: Native linking failed, undefined Objective-C class: MSWrapperSdk. The symbol '_OBJC_CLASS_$_MSWrapperSdk' could not be found in any of the libraries or frameworks linked with your application.

MTOUCH: error MT5202: Native linking failed. Please review the build log.

This is preventing development on device, I have to use my iOS simulator for all development or remove these packages from the project.

iOS | Device on Xamarin Studio mac is a supported configuration, right? ;)

**Comment by guperrot** [comment]
Hi, it works for me (in the demo app that is committed to this github repos), do you use version 0.5.0 and have you tried a clean build?

If you check out this repos and build the demo app for ios (Contoso.Forms.Demo.iOS), does it work for you?

Also we support only ios8+.

**Comment by yozzozo** [comment]
I'm using 0.5.0 on iOS 10.1, and have tried a clean rebuild several times
(including restarting the IDE and manually deleting the bin/obj folders).

I haven't tried your demo app, I'll try that and let you know if it works.

**Comment by guperrot** [comment]
Hi, any news on this @yozzozo?

**Comment by guperrot** [comment]
Have you tried upgrading Xamarin IDE and components? We had a similar report with outdated Xamarin tools.

**Comment by yozzozo** [comment]
Sorry for the delay getting back.

I just reinstalled Xamarin Studio on a brand new Mac and restored all my
NuGet packages and the issue went away.  Not sure why it happened as I was
completely up to date with the tools.  However, I did recently switch
Xamarin Studio to the alpha update channel and then back to stable... maybe
something related to that.



On Thu, Jan 19, 2017 at 11:49 AM Guillaume Perrot <notifications@github.com>
wrote:

Have you tried upgrading Xamarin IDE and components? We had a similar
report with outdated Xamarin tools.




—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/mobile-center-sdk-xamarin/issues/118#issuecomment-273879105>,
or mute the thread

**Comment by guperrot** [comment]
Glad to hear it works now.
Thanks for using Mobile Center.

**Comment by JelleDamen** [comment]
I'm getting this issue, even after switching/installing the latest alpha version of Visual Studio for Mac. I also tried Xamarin studio, but it showed the same errors.

```
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MSUserDefaults. The symbol '_OBJC_CLASS_$_MSUserDefaults' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MSAppDelegateForwarder. The symbol '_OBJC_CLASS_$_MSAppDelegateForwarder' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MSLogger. The symbol '_OBJC_CLASS_$_MSLogger' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_MSServiceAbstract. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MSServiceAbstract. The symbol '_OBJC_CLASS_$_MSServiceAbstract' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MSChannelConfiguration. The symbol '_OBJC_CLASS_$_MSChannelConfiguration' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_MSAbstractLog. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: MSAbstractLog. The symbol '_OBJC_CLASS_$_MSAbstractLog' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5202: Native linking failed. Please review the build log.
```
The strange thing is, that it only happend when I added the push package.
