### ISSUE TITLE
Attachments don't show up in Mobile Center

### ISSUE THREAD

**Issue by nathanielcook** [Microsoft/mobile-center-sdk-xamarin#119]
Crashes_GetErrorAttachment callback gets called. Verbose logging shows 
```
"os_exception_address" : "0x1171d0f06",
"os_exception_code" : "#0",
"error_attachment" : {
        "binary_attachment" : {
          "file_name" : "image.png",
          "data" : "mydatahere",
          "content_type" : "image/png"
        }
      }
```
and crash shows up in Mobile Center, but no attachment. Is the display of attachments associated with a crash not implemented yet in Mobile Center?

**Comment by guperrot** [comment]
Hi, this feature is not yet supported in the portal.

**Comment by nathanielcook** [comment]
Oh ok. I would recommend adding it to the roadmap.
